# Generated by Django 5.2.14 on 2026-05-09 19:57

import detector.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=detector.models.upload_to)),
                ('is_weapon', models.BooleanField(default=False)),
                ('confidence', models.FloatField(default=0.0)),
                ('predicted_label', models.CharField(default='Unknown', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Detection Result',
                'verbose_name_plural': 'Detection Results',
                'ordering': ['-created_at'],
            },
        ),
    ]
